# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtWidgets import (QPushButton, QHBoxLayout, QVBoxLayout, QTableView)
from PySide6 import QtCore


class Ui_cg_form(object):
    def setupUi(self, cg_form):
        cg_form.setObjectName("cg_form")
        cg_form.resize(500, 451)
        self.verticalLayout_2 = QVBoxLayout(cg_form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.supplier_item_add = QPushButton(cg_form)
        self.supplier_item_add.setObjectName("supplier_item_add")
        self.horizontalLayout.addWidget(self.supplier_item_add)
        self.supplier_item_delete = QPushButton(cg_form)
        self.supplier_item_delete.setObjectName("supplier_item_delete")
        self.horizontalLayout.addWidget(self.supplier_item_delete)
        self.supplier_item_save = QPushButton(cg_form)
        self.supplier_item_save.setObjectName("supplier_item_save")
        self.horizontalLayout.addWidget(self.supplier_item_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.supplier_table_view = QTableView(cg_form)
        self.supplier_table_view.setObjectName("supplier_table_view")
        self.verticalLayout.addWidget(self.supplier_table_view)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(cg_form)
        QtCore.QMetaObject.connectSlotsByName(cg_form)

    def retranslateUi(self, cg_form):
        _translate = QtCore.QCoreApplication.translate
        cg_form.setWindowTitle(_translate("cg_form", "Form"))
        self.supplier_item_add.setText(_translate("cg_form", "增加"))
        self.supplier_item_delete.setText(_translate("cg_form", "删除"))
        self.supplier_item_save.setText(_translate("cg_form", "保存"))
